#!/bin/sh

# zPodcast - by Zorge.R - Motofan.ru
# plese don't modify code.

showRadio "$zp_NAME_APP" "$zp_CP_motofan_mini" "$zp_radio_lstn" "$zp_radio_list" "$zp_rd_op DFM" "$zp_rd_op radio21.Romania" "$zp_rd_op RusRadio" "$zp_rd_op Europa Plus"

ret=$?
[ $ret -eq 0 ] && $zpodpath/init

case $ret in
	1)	
		showTextEntry "$zpodpath/custom.radio.url" "$zp_NAME_APP" "$zp_radio_url" 0
		radiourl=`cat $zpodpath/custom.radio.url`
		if [ "$radiourl" != 0 ] && [ "$radiourl" != "" ]
		then
		dolisten
		fi
		. $zpodpath/init
		;;
	2)	
		# Парсим список радиостанций radio.list, для вывода юзеру
		radiolist=`awk -F\= '{print $1}' $zpodpath/radio.list`
		# Отображаем список радиостанций
		showRadio "$zp_NAME_APP" "Radio.list" $radiolist
		RADIORES=$?
		if [ $RADIORES -eq 0 ]
		then
			# если отмена, переходим в "RADIO"
			. $zpodpath/radio
		else
			# захватываем название выбранной станции
			radioname=`sed -n $RADIORES\p $zpodpath/radio.list | awk -F\= '{print $1}'`
			# захватываем URL выбранной станции
			radiourl=`sed -n $RADIORES\p $zpodpath/radio.list | awk -F\= '{print $2}'`
			# Запуск мплеера
			dolisten
		fi
		;;
	3)	
		radiourl="http://w02-sw01.akadostream.ru:8000/dinamitfm128.mp3"
		radioname="DFM"
		dolisten
		;;
	4)	
		radiourl="http://89.238.252.138:8000"
		radioname="radio21.Romania"
		dolisten
		;;
	5)	
		radiourl="http://w02-sw01.akadostream.ru:8000/russianradio128.mp3"
		radioname="Russian Radio"
		dolisten
		;;
	6)	
		radiourl="http://w02-sw01.akadostream.ru:8000/europaplus128.mp3"
		radioname="Europa Plus"
		dolisten
		;;
	*)
		;;
esac

